<?php
/**
 * Created by PhpStorm.
 * User: liyassoladogun
 * Date: 11/13/18
 * Time: 9:35 PM
 */

namespace Training\S1v6\Controller\Index;


use Magento\Framework\App\Action\Context;
use Magento\Framework\App\RequestInterface;
use Psr\Log\LoggerInterface;

class Index extends \Magento\Framework\App\Action\Action
{
    private $pageFactory;
    private $logger;
    public function __construct(Context $context,
                            \Magento\Framework\View\Result\PageFactory $pageFactory,
                            LoggerInterface $logger)
    {
        $this->pageFactory = $pageFactory;
        $this->logger = $logger;
        parent::__construct($context);
    }

    /**
     * @param RequestInterface $request
     * @param string $test
     * @return \Magento\Framework\App\ResponseInterface
     * @throws \Magento\Framework\Exception\NotFoundException
     */
    public function dispatch(RequestInterface $request, $test = 'parent dispatch')
    {
        $this->logger->info('Module Action Dispatch Method is called', [$request, $test]);
        return parent::dispatch($request); // TODO: Change the autogenerated stub
    }

    /**
     * @return \Magento\Framework\Controller\ResultInterface
     */
    public function execute()
    {
      return $this->pageFactory->create();
    }
}