<?php
/**
 * Created by PhpStorm.
 * User: liyassoladogun
 * Date: 11/12/18
 * Time: 9:21 PM
 */

namespace Training\S1v1\Model;


class PaymentTokenManagement extends \Magento\Vault\Model\PaymentTokenManagement
{

   public function addLinkToOrderPayment($paymentTokenId, $orderPaymentId)
   {
       return parent::addLinkToOrderPayment($paymentTokenId, $orderPaymentId); // TODO: Change the autogenerated stub
   }

}